### GET all guests

GET http://localhost:4545/guests


### GET only confirmed guests

GET http://localhost:4545/guests?status=confirmed


### GET only declined guests

GET http://localhost:4545/guests?status=declined


### GET 2nd user

GET http://localhost:4545/guests/2


### Add new guest HAPPY PATH

POST http://localhost:4545/guests
Content-Type: application/json

{
    "name": "Barbara2",
    "lastName": "Gordon"
}


### Add new guest SAD PATH (missing name)

POST http://localhost:4545/guests
Content-Type: application/json

{}

### Usuń gościa o id 90

DELETE http://localhost:4545/guests/90
Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30