services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 5070:8081

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234!
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234!
      ME_CONFIG_MONGODB_URL: mongodb://root:1234!@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mysql:
    image: mysql
    restart: always
    ports:
      - 3366:3306
    environment:
      MYSQL_DATABASE: sql-database
      MYSQL_ROOT_PASSWORD: 1234!

  adminer:
    image: adminer
    restart: always
    ports:
      - 5090:8080

volumes:
  redis_data:
  mongo_data:
